Pages/AdminPanel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class AdminPanel : PageModel
    {
        private readonly ILogger<AdminPanel> _logger;
        private readonly ApplicationDbContext _db;

        public AdminPanel(ILogger<AdminPanel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public Intern Intern { get; set; }
        public InternSubmitted InternSubmitted { get; set; }

        public async Task<IActionResult> OnGet()
        {
            
            return Page();
        }


        [BindProperty(Name = "companyName")]
        public String postCompanyName { get; set; }

        [BindProperty(Name = "position")]
        public String postPosition { get; set; }

        [BindProperty(Name = "details")]
        public String postDetails { get; set; }
        public async Task<IActionResult> OnPost()
        {
            Intern newIntern = new Intern();
            newIntern.CompanyName = postCompanyName;
            newIntern.Position = postPosition;
            newIntern.Details = postDetails;
            newIntern.OpenTime = DateTime.Now;

            await _db.Intern.AddAsync(newIntern);
            await _db.SaveChangesAsync();
            return Page();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace StajyerUygulamasi.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StajyerUygulamasi.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return RedirectToPage("Interns");
        }
    }
}

Pages/Interns.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class InternsModel : PageModel
    {
        private readonly ILogger<InternsModel> _logger;
        private readonly ApplicationDbContext _db;

        public InternsModel(ILogger<InternsModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public Intern Intern { get; set; }
        public IActionResult OnGet()
        {
            var loginStajyerID = HttpContext.Session.GetInt32("loginStajyerID");
            if (loginStajyerID == null)
            {
                TempData["LoginMessage"] = "Oturumunuzun süresi doldu!";
                return RedirectToPage("Login");
            }
            List<Intern> interns = _db.Intern.ToList();
            ViewData["Interns"] = interns;
            return Page();
        }

    }
}

Pages/InternsDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StajyerUygulamasi.Dto;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class InternsDetailModel : PageModel
    {
        private readonly ILogger<InternsDetailModel> _logger;
        private readonly ApplicationDbContext _db;

        public InternsDetailModel(ILogger<InternsDetailModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public Intern Intern { get; set; }
        public InternSubmitted InternSubmitted { get; set; }

        [BindProperty(SupportsGet = true)]
        public int internID { get; set; }
        public async Task<IActionResult> OnGet()
        {
            var loginStajyerID = HttpContext.Session.GetInt32("loginStajyerID");
            if (loginStajyerID == null)
            {
                TempData["LoginMessage"] = "Oturumunuzun süresi doldu!";
                return RedirectToPage("Login");
            }
            if (internID == 0)
            {
                return RedirectToPage("Error");
            }
            Intern intern = await _db.Intern.FindAsync(keyValues: internID);
            InternSubmitted foundedSubmittedIntern = await _db.InternSubmitted.FirstOrDefaultAsync(dbInternSubmitted => dbInternSubmitted.StajyerID.Equals(loginStajyerID) && dbInternSubmitted.InternID.Equals(internID));

            InternDto internDto = new InternDto();
            internDto.Id = intern.Id;
            internDto.Position = intern.Position;
            internDto.ApplicantsCounter = intern.ApplicantsCounter;
            internDto.Details = intern.Details;
            internDto.CompanyName = intern.CompanyName;
            internDto.OpenTime = intern.OpenTime;
            if (foundedSubmittedIntern != null)
            {
                internDto.isAplied = true;
            }
            
            ViewData["Intern"] = internDto;
            return Page();
        }

        [BindProperty(Name = "internID")]
        public int postInternID { get; set; }
        public async Task<IActionResult> OnPost()
        {
            Intern foundedIntern = await _db.Intern.FindAsync(postInternID);
            foundedIntern.ApplicantsCounter = foundedIntern.ApplicantsCounter + 1;

            InternSubmitted internSubmitted = new InternSubmitted();
            internSubmitted.SubmitTime = DateTime.Now;
            internSubmitted.InternID = postInternID;
            internSubmitted.StajyerID = (int)HttpContext.Session.GetInt32("loginStajyerID");
            await _db.InternSubmitted.AddAsync(internSubmitted);
            await _db.SaveChangesAsync();
            return RedirectToPage("InternsSubmitted");
        }

    }
}

Pages/InternsSubmitted.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class InternsSubmitted : PageModel
    {
        private readonly ILogger<InternsSubmitted> _logger;
        private readonly ApplicationDbContext _db;

        public InternsSubmitted(ILogger<InternsSubmitted> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public Intern Intern { get; set; }
        public InternSubmitted InternSubmitted { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var loginStajyerID = HttpContext.Session.GetInt32("loginStajyerID");
            if (loginStajyerID == null)
            {
                TempData["LoginMessage"] = "Oturumunuzun süresi doldu!";
                return RedirectToPage("Login");
            }
            List<InternSubmitted> internsSubmitted = await _db.InternSubmitted.Where(dbInternSubmitted => dbInternSubmitted.StajyerID.Equals(loginStajyerID)).ToListAsync();
            List<Intern> interns = await _db.Intern.Where(dbIntern => internsSubmitted.Select(submitted => submitted.InternID).Contains(dbIntern.Id)).ToListAsync();
            ViewData["InternsSubmitted"] = interns;
            ViewData["stajyerID"] = loginStajyerID;
            return Page();
        }


        [BindProperty(Name = "internID")]
        public int postInternID { get; set; }

        [BindProperty(Name = "stajyerID")]
        public int postStajyerID { get; set; }
        public async Task<IActionResult> OnPost()
        {
            Intern foundedIntern = await _db.Intern.FindAsync(postInternID);
            foundedIntern.ApplicantsCounter = foundedIntern.ApplicantsCounter - 1;

            InternSubmitted internSubmitted = await _db.InternSubmitted.FirstOrDefaultAsync(dbInternSubmitted => dbInternSubmitted.InternID == postInternID && dbInternSubmitted.StajyerID == postStajyerID);
            _db.InternSubmitted.Remove(internSubmitted);
            await _db.SaveChangesAsync();
            return RedirectToPage("InternsSubmitted");
        }
    }
}

Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<LoginModel> _logger;
        private readonly ApplicationDbContext _db;

        public LoginModel(ILogger<LoginModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }
        [BindProperty(Name = "email")]
        public string postEmail { get; set; }
        [BindProperty(Name = "password")]
        public string postPassword { get; set; }

        public void OnGet()
        {

        
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid) {
                var userLoginSuccess = await _db.Stajyer.FirstOrDefaultAsync(dbStajyer => dbStajyer.Email == postEmail && dbStajyer.Password == postPassword);

                if (userLoginSuccess != null) {
                    HttpContext.Session.SetInt32("loginStajyerID", userLoginSuccess.Id);
                    HttpContext.Session.SetString("loginStajyerName", userLoginSuccess.Name);
                    HttpContext.Session.SetString("loginStajyerSurname", userLoginSuccess.Surname);
                    return Redirect("Interns");
                }
                else {
                    TempData["LoginMessage"] = "Email yada parola hatalı.";
                    return Page();
                }
            } 
            else {
                TempData["LoginMessage"] = "Lütfen eksik bilgileri doldurunuz.";
                return Page();
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StajyerUygulamasi.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StajyerUygulamasi.Model;

namespace StajyerUygulamasi.Pages
{
    public class ProfileModel : PageModel
    {
        private readonly ILogger<ProfileModel> _logger;
        private readonly ApplicationDbContext _db;

        public ProfileModel(ILogger<ProfileModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public About About { get; set; }
        public Skill Skill { get; set; }
        public Experience Experience { get; set; }
        public Education Education { get; set; }

        public async Task<IActionResult> setPageData()
        {
            var loginStajyerID = HttpContext.Session.GetInt32("loginStajyerID");
            if (loginStajyerID == null)
            {
                TempData["LoginMessage"] = "Oturumunuzun süresi doldu!";
                return RedirectToPage("Login");
            }
            else
            {
                var dbAbout = await _db.About.FindAsync(keyValues: HttpContext.Session.GetInt32("loginStajyerID"));
                if (dbAbout == null)
                {
                    TempData["AboutText"] = "";
                    TempData["AboutBirthDate"] = null;
                }
                else
                {
                    if (dbAbout.AboutText == null)
                    {
                        TempData["AboutText"] = "";
                    }
                    else
                    {
                        TempData["AboutText"] = dbAbout.AboutText;
                    }

                    TempData["AboutBirthDate"] = dbAbout.DateOfBirth;
                }

                List<Experience> dbExperience = await _db.Experience.Where(dbExperience => dbExperience.StajyerID == HttpContext.Session.GetInt32("loginStajyerID")).ToListAsync();

                TempData["Experiences"] = dbExperience;

                List<Education> dbEducation = await _db.Education.Where(dbEducation => dbEducation.StajyerID == HttpContext.Session.GetInt32("loginStajyerID")).ToListAsync();

                TempData["Educations"] = dbEducation;

                List<Skill> dbSkill = await _db.Skill.Where(dbSkill => dbSkill.StajyerID == HttpContext.Session.GetInt32("loginStajyerID")).ToListAsync();

                TempData["Skills"] = dbSkill;

                return Page();
            }
        }

        public async Task<IActionResult> OnGet()
        {
            return await setPageData();
        }

        public async Task<IActionResult> OnPostAbout(string aboutMe, DateTime birthday)
        {
            if (aboutMe != null && birthday != null)
            {
                var dbAbout = await _db.About.FindAsync(keyValues: HttpContext.Session.GetInt32("loginStajyerID"));


                if (dbAbout != null)
                {
                    dbAbout.AboutText = aboutMe;
                    dbAbout.DateOfBirth = birthday;
                }
                else
                {
                    About newAbout = new About();
                    newAbout.AboutText = aboutMe;
                    newAbout.DateOfBirth = birthday;
                    newAbout.StajyerID = (int)HttpContext.Session.GetInt32("loginStajyerID");
                    await _db.About.AddAsync(newAbout);
                }
                await _db.SaveChangesAsync();
            }

            return await setPageData();
        }

        public async Task<IActionResult> OnPostSkill(string skill)
        {   
            if (skill != null)
            {
                Skill newSkill = new Skill();
                newSkill.SkillName = skill;
                newSkill.StajyerID = (int)HttpContext.Session.GetInt32("loginStajyerID");
                await _db.Skill.AddAsync(newSkill);
                await _db.SaveChangesAsync();
            }

            return await setPageData();
        }

        public async Task<IActionResult> OnPostExperience(string experienceCompanyName, string experiencePosition, DateTime experienceStartingDate, DateTime experienceFinishDate)
        {
            if (experienceCompanyName != null && experiencePosition != null && experienceStartingDate != null && experienceFinishDate != null)
            {
                Experience newExperience = new Experience();
                newExperience.CompanyName = experienceCompanyName;
                newExperience.Position = experiencePosition;
                newExperience.StartTime = experienceStartingDate;
                newExperience.FinishTime = experienceFinishDate;
                newExperience.StajyerID = (int)HttpContext.Session.GetInt32("loginStajyerID");
                await _db.Experience.AddAsync(newExperience);
                await _db.SaveChangesAsync();
            }

            return await setPageData();
        }

        public async Task<IActionResult> OnPostEducation(string educationSchoolName, DateTime educationStartingDate, DateTime educationFinishDate)
        {
            if (educationSchoolName != null)
            {
                Education newEducation = new Education();
                newEducation.EducationName = educationSchoolName;
                newEducation.StartTime = educationStartingDate;
                newEducation.FinishTime = educationFinishDate;
                newEducation.StajyerID = (int)HttpContext.Session.GetInt32("loginStajyerID");
                await _db.Education.AddAsync(newEducation);
                await _db.SaveChangesAsync();
            }

            return await setPageData();
        }
    }
}

Pages/AdminPanel.cshtml
@page
@model AdminPanel
@using StajyerUygulamasi.Model
@{
    ViewData["Title"] = "AdminPanel";
}
<head>
    <meta charset="utf-8" />
</head>

<div class="text-center">
    <h2>Admin Paneli</h2>

    <div class="border border-3 mt-4 p-4">
        <h3>Stajyer Arama İlanı Ekleme</h3>
        <form method="post" form asp-page-handler="InternAdd">
            <div class="mt-4">
                <input type="text" name="CompanyName" placeholder="Şirket İsmi" />
                <input type="text" name="Position" placeholder="Pozisyon" />
            </div>
            <div class="mt-4">
                <label for="details">Detaylar</label>
                <textarea id="details" style="width: 100%; height: 300px" type="text" name="Details"></textarea>
            </div>
            
            <input type="submit" value="Ekle"/>
        </form>
    </div>

    
</div>
<script>
    
</script>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a href="login">Login</a><br/>
    <a href="register">Register</a><br />
    <a href="interns">Interns</a><br />
    <a href="profile">Profile</a><br />
    <a href="internsSubmitted">InternsSubmitsted</a><br />
    <a href="adminPanel">Admin Panel</a>
</div>

Pages/Interns.cshtml
@page
@model StajyerUygulamasi.Pages.InternsModel
@using StajyerUygulamasi.Model
@{
    ViewData["Title"] = "Interns";
    var interns = (List<Intern>)ViewData["Interns"];
}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/interns-style.css" />
</head>
<div class="text-center">
    <div class="container mt-5 mb-3">
        <div class="row">

            @foreach (var intern in interns)
            {

                <div class="col-md-4">
                    <div class="card p-3 mb-2" id="@intern.Id">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                                <div class="ms-2 c-details">
                                    <h6 class="mb-0">@intern.CompanyName</h6> <span>@intern.OpenTime</span>
                                </div>
                            </div>
                        </div>
                        <div class="mt-5">
                            <h3 class="heading">@intern.Position</h3>
                            <div class="mt-5">
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            
                                 <div class="mt-3"> <span class="text1">@intern.ApplicantsCounter kişi başvurdu!</span> </div>
                                   
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

<script type="module" src="~/js/interns.js" asp-append-version="true"></script>

Pages/InternsDetail.cshtml
@page
@model StajyerUygulamasi.Pages.InternsDetailModel
@using StajyerUygulamasi.Dto
@{
    ViewData["Title"] = "Interns";
    InternDto intern = (InternDto)ViewData["Intern"];
}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/internsdetail-style.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>

<div class="text-center">
    <form method="post">
        <div class="card p-3 mb-2" id="@intern.Id">
            <div class="d-flex">
                <div class="d-flex flex-row align-items-center">
                    <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                    <div class="ms-2 c-details">
                        <h6 class="mb-0">@intern.CompanyName</h6> <span>@intern.OpenTime</span>
                    </div>
                    
                </div>
                
            </div>
            <h3 class="heading m-auto">@intern.Position</h3>
            <div class="mt-5">
                <div>
                <div> <p class="detail m-5" id="internDetails"></p> </div>
                    <input hidden value="@intern.Id" name="internID" />
                    <div class="mt-5"> <span class="text1">@intern.ApplicantsCounter kişi başvurdu!</span> </div>
                    @if (intern.isAplied == false)
                    {
                        <input type="submit" id="submitBtn" value="Başvur!" class="btn btn-success btn-icon-text mt-2" />
                    }
                    else
                    {
                        <input type="submit" id="submitBtn" value="Zaten Başvuruldu" class="btn btn-success btn-icon-text mt-2" disabled/>
                    }
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    let detailText = ("@intern.Details").toString().replaceAll("&#xD;&#xA;", "\r\n");
    document.getElementById("internDetails").innerText = detailText
</script>

Pages/Profile.cshtml
@page
@model ProfileModel
@using Microsoft.AspNetCore.Http
@using StajyerUygulamasi.Model
@{
    ViewData["Title"] = "Your Profile";
    var loginStajyerName = HttpContext.Session.GetString("loginStajyerName");
    var loginStajyerSurname = HttpContext.Session.GetString("loginStajyerSurname");
    var aboutText = TempData["AboutText"];
    var aboutBirthDate = "";
    if (TempData["AboutBirthDate"] != null)
    {
        var aboutBirthDateSplitted = TempData["AboutBirthDate"].ToString().Split(" ")[0].Split("/");
        aboutBirthDate = aboutBirthDateSplitted[2] + "-" + aboutBirthDateSplitted[1] + "-" + aboutBirthDateSplitted[0];
    }
    else
    {
        aboutBirthDate = "2001-07-28";
    }

    var experiences = (List<Experience>)TempData["Experiences"];
    var educations = (List<Education>)TempData["Educations"];
    var skills = (List<Skill>)TempData["Skills"];
}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/profile-style.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>

<div class="text-center">
    <div class="col-md border border-grey p-5">
        <div class="profileTopBar">
            <div class="profilePhoto">
            </div>
            <h3 id="profileNameSurname">@loginStajyerName @loginStajyerSurname</h3>
        </div>  
        <button class="btn btn-success btn-sm rounded-0 mt-3 closed" id="edit" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i> Bilgileri Düzenle</button>
        <div class="mt-4">
            <form asp-page-handler="About" method="post">
                <div class="row gx-2 border border-grey p-2">
                    <h4>Hakkımda</h4>
                    <div class="form-floating mb-3 mt-3">
                        <textarea class="form-control" id="aboutMe" style="height: 100px" name="aboutMe" disabled>@aboutText</textarea>
                        <label for="aboutMe">Hakkımda</label>
                    </div>
                    <div class="col input-group mb-3">
                        <span class="input-group-text">Doğum Tarihi</span>
                        <input class="dateInput form-control" type="date" id="birthday" name="birthday" value="@aboutBirthDate" disabled>
                    </div>
                    <div class="col-3 input-group editableArea" style="display:none">
                        <button type="submit" class="btn btn-secondary">Kaydet</button>
                    </div>
                </div>
            </form>
        
            <div class="row gx-2 border border-grey p-2">
                <h4>Deneyim</h4>
                <table class="table" id="experience">
                    <tbody>
                        @if (experiences.Count > 0)
                        {
                            <tr>
                                <th>Şirket Adı</th>
                                <th>Pozisyon</th>
                                <th>Başlama Zamanı</th>
                                <th>Bitiş Zamanı</th>
                            </tr>
                        }
                        else
                        {
                            <span>Deneyim geçmişi bulunamadı.</span>
                        }
                        @foreach (var experience in experiences)
                        {
                            <tr>
                                <td>@experience.CompanyName</td>
                                <td>@experience.Position</td>
                                <td>@experience.StartTime.ToString().Split(" ")[0]</td>
                                <td>@experience.FinishTime.ToString().Split(" ")[0]</td>
                            </tr>
                        }
                    </tbody>
                </table>
                
                
                <form asp-page-handler="Experience" method="post" class="row gx-4 editableArea" style="display:none">
                    <div class="col input-group">
                        <span class="input-group-text">Şirket Adı</span>
                        <input type="text" class="form-control" id="experienceCompanyName" name="experienceCompanyName">
                    </div>
                    <div class="col input-group">
                        <span class="input-group-text">Posizyon</span>
                        <input type="text" class="form-control" id="experiencePosition" name="experiencePosition">
                    </div>
                    <div class="col input-group">
                        <span class="input-group-text">Başlama Tarihi</span>
                        <input class="dateInput form-control" type="date" id="experienceStartingDate" name="experienceStartingDate">
                    </div>
                    <div class="col input-group">
                        <span class="input-group-text">Bitiş Tarihi</span>
                        <input class="dateInput form-control" type="date" id="experienceFinishDate" name="experienceFinishDate">
                    </div>
                    <div class="col input-group">
                        <button type="submit" class="btn btn-secondary">+</button>
                    </div>
                </form>
                
                
            </div>

            <div class="row gx-2 border border-grey p-2">
                <h4>Eğitim</h4>
                <table class="table" id="education">
                    <tbody>
                        @if (educations.Count > 0)
                        {
                            <tr>
                                <th>Okul Adı</th>
                                <th>Başlama Zamanı</th>
                                <th>Bitiş Zamanı</th>
                            </tr>
                        }
                        else
                        {
                            <span>Eğitim geçmişi bulunamadı.</span>
                        }
                        @foreach (var education in educations)
                        {
                            <tr>
                                <td>@education.EducationName</td>
                                <td>@education.StartTime.ToString().Split(" ")[0]</td>
                                <td>@education.FinishTime.ToString().Split(" ")[0]</td>
                            </tr>
                        }
                    </tbody>
                </table>
                
                <form asp-page-handler="Education" method="post" class="row gx-4 editableArea" style="display:none">
                    <div class="col input-group">
                        <span class="input-group-text">Okul Adı</span>
                        <input type="text" class="form-control" id="educationSchoolName" name="educationSchoolName">
                    </div>

                    <div class="col input-group">
                        <span class="input-group-text">Başlama Tarihi</span>
                        <input class="dateInput form-control" type="date" id="educationStartingDate" name="educationStartingDate">
                    </div>

                    <div class="col input-group">
                        <span class="input-group-text">Bitiş Tarihi</span>
                        <input class="dateInput form-control" type="date" id="educationFinishDate" name="educationFinishDate">
                    </div>
                    <div class="col input-group">
                        <button type="submit" class="btn btn-secondary">+</button>
                    </div>
                </form>
                
            </div>

            <div class="row gx-2 border border-grey p-2">
                <h4>Yetenekler</h4>
                <div class="container text-center">
                    <div class="row" id="skillsTab">
                        @if (skills.Count > 0)
                        {
                            @foreach (var skill in skills)
                            {
                                <div class="col-md-4 border border-grey p-3 m-2">
                                    @skill.SkillName
                                </div>
                            }
                        }
                        else
                        {
                            <span>Yetenek ekleyin!</span>
                        }
                    </div>
                </div>

                <form asp-page-handler="Skill" method="post" class="input-group mb-3 editableArea" style="display:none">
                    <span class="input-group-text" id="basic-addon1">Yetenek Ekle</span>
                    <div class="col-2">
                        <input type="text" class="form-control" name="skill" id="skill">
                    </div>
                    <button type="submit" class="btn btn-secondary">+</button>
                </form>
                
            </div>
         </div>
    </div>
</div>

<script type="module" src="~/js/profile.js" asp-append-version="true"></script>